# Site settings
title: Lucas Nunno's portfolio site
homepage_name: Lucas Nunno
email: lucasnunno@gmail.com
baseurl: ""
imageurl: "/assets/images"
docurl: "/assets/docs"
url: "http://lnunno.github.io"
linkedin_username: lnunno
github_username:   lnunno

social_badge_size: "2x"

# Build settings
markdown: kramdown
permalink: pretty