# Site settings
title: Lucas Nunno
email: lnunno@cs.unm.edu
description: "This is Lucas Nunno's portfolio website. It showcases the work that I have done, along with descriptions of my software engineering philosophy."
baseurl: ""
imageurl: "/assets/images"
docurl: "/assets/docs"
url: "http://lnunno.github.io"
linkedin_username: lnunno
github_username:   lnunno

social_badge_size: "2x"

# Build settings
markdown: kramdown
permalink: pretty
