# Site settings
title: Lucas Nunno's Portfolio Site
email: lnunno@cs.unm.edu
description: "This is my portfolio which showcases the work that I have done, along with descriptions of my software engineering philosophy."
baseurl: ""
url: "http://yourdomain.com"
linkedin_username: lnunno
github_username:  lnunno

# Build settings
markdown: kramdown
permalink: pretty
